### ISSUE TITLE
Compatibility with Atelier

### ISSUE THREAD

**Issue by daimor** [rfns/port#1]
Hi, this project looks interesting, but how about compatibility with Atelier. As I see, you add `.txt` extension to all files, and I don't understand, why?

**Comment by rfns** [comment]
Hi, thanks for your opinion regarding _port_. 

Now answering your question, that's due to **github** getting lost when listing which languages are related to the project. Really, that's the only (stupid) reason.

I noticed that it lists languages like Apex, TeX and a few others if I keep the original extensions. So in order to prevent this _port_ appends a` .txt` to each file except files from the web path (since they're aren't necessarily CSP files). Ex: .js, .css, etc.

However, I agree that for projects that aren't hosted on github it might be a good idea to keep the original extensions, so I'm going to add a setting to disable it.

About Atelier, uhmm, yeah. I'm looking about it, however I started using it recently so I don't know that much about it's internal features yet.  If you want to contribute along with the idea of integrating support to Atelier you're more than welcome to open a PR. Atelier would have been my first target if I hadn't started _port_ before it was announced.

**Comment by evshvarov** [comment]
Actually, we introduced highlight support for COS in Github, but GitHub agreed to add the highlighing support in the interface if it would be at least 100+ projects with this type of source code. So, @rfns maybe you'll introduce at least a folder with .cls, .inc, mac files? Just to let us point your repo as UDL?

**Comment by evshvarov** [comment]
Another question to discuss: what is the good github topic for udl? intersystems-udl? just udl? or caché-objectscript-udl? Any ideas?

**Comment by daimor** [comment]
I think just `intersystems` will be enough

**Comment by evshvarov** [comment]
@daimor intersystems is good but it points to a lot of projects with xml sources too.

**Comment by daimor** [comment]
@evshvarov is it really matter? I don't see any reasons to add such specific topic for UDL sources, in future I hope all repositories will store only UDL, so, what we will do in this case. Actually, this topic contains all repositories related to InterSystems, even not in CacheObjectScript. Maybe topic `intersystems-cos` would be better, but not matter UDL or XML.

**Comment by rfns** [comment]
@evshvarov Interesting, I didn't know there was already such a pending request for Github.

I'll update this repo to use native Caché extensions. Hold on.

**Comment by rfns** [comment]
Done!

https://github.com/rfns/port/commit/6b031cd10fb12185663f80bcba286427030dd762 removed all extension suffixes.

**Comment by evshvarov** [comment]
Hi, @rfns!
We introduced the topic [cacheobjectscript-udl](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acacheobjectscript-udl&type=Repositories) which will gather open projects with COS in UDL form. Would you please add this topic to your repos? 
It would help us greatly to gather 100 projects with UDL and introduce the language support on Github! 
Thank you in advance!

**Comment by rfns** [comment]
@evshvarov Added.
