### ISSUE TITLE
Publish it on Open Exchange?

### ISSUE THREAD

**Issue by evshvarov** [rfns/port#5]
would be great if you could submit it on[ InterSystems Open Exchange](https://openexchange.intersystems.com)

**Comment by rfns** [comment]
@evshvarov Hello, I'm actually rewriting most of it by removing deprecated features and making an reusable API by breaking it into modules. The current version on this repository is not stable enough. The problem is, I've been prioritizing other projects.

Regarding the issues, I'll give you two cases:

* Instability when using MultiValue routines, sadly this is actually a  feature I plan to remove, since I haven't seen many developers use it and the API for its management is pretty obscure.

* Support for static files (in _Port_ I call it "web" files, because it isn't limited to CSP files anymore), the current published version is incapable of detecting a valid web application which has actually a physical path, because it used to depend on GetDefaultApp method. This has been changed already as it attempts to find an application that is not REST for the selected namespace, but I still must implement an entry point to configure it.

Meanwhile you might want to check out the [Frontier](https://github.com/rfns/frontier/tree/pre-release/v5), which is a framework for developing REST applications for Caché.

And [Forgery](https://github.com/rfns/forgery) a toolkit for mimicking requests to REST classes without actually using the network. Ideal for UnitTests.

Finally, I've been working on a extension that could be used as an companion to the Dmitry's  [vscode-objectscript](https://github.com/daimor/vscode-objectscript), I haven't published it yet, but you can think on something bringing Port features to VSCode.

Here's a sample https://imgur.com/a/bv1s5vE. I call it XPort.
